---
title: "About microbiomeutilities"
author: "Sudarshan A. Shetty"
---

# Development stage 

**This package is in experimental stage and should be used with caution** 
I will keep improving this with time and feedback.  

# microbiomeutilities
This is mainly a _wrapper tool R package_. Apart for some simple scripts for plotting, this package has a single function `microbiome_pipeline` for carrying out preliminary QC, Alpha Diversity, Ordination and Composition analysis of OTU tables. The output is a _HTML_ report for convenient investigating of the data.     

Example output of the `microbiome_pipeline`: [Mock](reference/Mock_report.html).   

**Install microbiomeutilities**   

```{r, eval=FALSE}

install.packages("devtools")

devtools::install_github("microsud/microbiomeutilities")

```  

**NOTE** The aim of this package is not to replace any of the following tools, instead this package is useful for a quick and (not so) dirty analysis of the OTU tables/biom files generated by tools such as QIIME (the newer QIIME2) (Caporaso, Kuczynski, Stombaugh et al., 2010), Mothur (Schloss, Westcott, Ryabin et al., 2009), DADA2 (Callahan, McMurdie, Rosen et al., 2016). Use the _HTML_ report as a reference guide and not consider it as final results.      

## Why do this?  
I am a microbiologists and R enthusiast and some times, my free time activity includes combining these two. The learning curve is steep for analysing microbiome data from scratch. This package includes codes that are used routinely by me and my collegues and friends. Realsing that the entire process of analysing microbiome data is iterative and requires investment of time for thorough analysis, it was useful for me to make a package which makes this a little simpler. This helps in planning better the individual analysis such as filtering, normalisation, transformation (all three are topics of hot debate and disagreement). The ability to look quickly if the main factor of interst is having an impact on the community diversity, composition, structure can be useful. This will also helps in making better decisions for further in-depth analysis. 
Immediate use can be for people who are working with enrichments and want basic analysis such as microbial composition of different enrichment conditions.     

## Direction for this package   
Depending on the real world usefulness, practicality and success, we plan to include complete or parts of this package in the Microbiome R package.  
"Leo Lahti, Sudarshan Shetty [et al.](https://github.com/microbiome/microbiome/graphs/contributors) ([Bioconductor, 2017](https://bioconductor.org/packages/devel/bioc/html/microbiome.html)). Tools for microbiome analysis in R.   

The microbiome R package relies on the independently developed   
[phyloseq](https://github.com/joey711/phyloseq) package and data structures for R-based microbiome analysis developed by Paul McMurdie and Susan Holmes.  
[ggplot2](http://ggplot2.org/) H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York, 2009.  
[tidyverse packages](https://www.tidyverse.org/).  



**Microbiome package website with easy tutorials**:  
URL: [http://microbiome.github.com/microbiome](http://microbiome.github.com/microbiome).  

 
_OTU or ASVs amplicon sequence variants as suggested recently (Callahan, McMurdie & Holmes, 2017)_.   
